const normalizeStatusToken = (value) =>
    String(value || "")
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_+|_+$/g, "")
        .replace(/_+/g, "_");

const STATUS_LABELS = {
    active: "Ativo",
    amended: "Alterado",
    approved: "Aprovado",
    archived: "Arquivado",
    available: "Disponível",
    awaiting_approval: "Aguardando Aprovação",
    awaiting_judgement: "Aguardando Julgamento",
    awaiting_partial_shipment_response: "Aguardando Resposta de Envio Parcial",
    awaiting_qualification: "Aguardando Qualificação",
    awaiting_shipment: "Aguardando Envio",
    awaiting_supplement: "Aguardando Complemento",
    being_received: "Em Recebimento",
    blocked: "Bloqueado",
    busy: "Ocupado",
    canceled: "Cancelado",
    cancelled: "Cancelado",
    cancelado: "Cancelado",
    cash: "Cash",
    closed: "Fechado",
    completed: "Concluído",
    concluido: "Concluído",
    delivered: "Entregue",
    entregue: "Entregue",
    disqualified: "Desclassificado",
    draft: "Rascunho",
    eligible: "Habilitado",
    expired: "Expirado",
    failed: "Falhou",
    fully_shipped: "Totalmente Enviado",
    fully_used: "Totalmente Utilizado",
    in_progess: "Em Progresso",
    in_progress: "Em Progresso",
    in_store: "In-store",
    in_review: "Em Revisão",
    in_sorting: "Em Distribuição",
    sorting: "Em Distribuição",
    in_training: "Em Treinamento",
    in_transit: "Em Trânsito",
    em_transporte: "Em Trânsito",
    inactive: "Inativo",
    ineligible: "Inabilitado",
    integrated: "Integrado",
    invited: "Convidado",
    invoiced: "Faturado",
    expedicao_envio: "Faturado",
    expedicao: "Faturado",
    envio: "Faturado",
    item_implemented: "Item Implantado",
    judgement: "Em Julgamento",
    maintenance: "Em Manutenção",
    mundimed_review: "Em Revisão Mundimed",
    no_bids_received: "Sem Propostas",
    not_approved: "Não Aprovado",
    offline: "Offline",
    online: "Online",
    walk_in: "Walk-in",
    walkin: "Walk-in",
    on_break: "Em Pausa",
    on_leave: "Afastado",
    open: "Aberto",
    outlet: "Outlet",
    partial_received: "Recebido Parcial",
    partial_shipment_approved: "Envio Parcial Aprovado",
    partial_shipment_rejected: "Envio Parcial Rejeitado",
    partially_delivered: "Parcialmente Entregue",
    partially_in_force: "Parcialmente Vigente",
    partially_invoiced: "Parcialmente Faturado",
    partially_returned: "Parcialmente Devolvido",
    partially_shipped: "Parcialmente Enviado",
    partially_used: "Parcialmente Utilizado",
    passwordexpired: "Senha Expirada",
    pending: "Pendente",
    pendingactivation: "Aguardando Ativação",
    pendingdeletion: "Aguardando Exclusão",
    picking_in_progress: "Separação em Andamento",
    qualified: "Qualificado",
    qualified_awaiting_commitment: "Aguardando Empenho",
    qualified_purchase_order_issued: "Ordem de Compra Gerada",
    quoted: "Cotado",
    rejected: "Rejeitado",
    rejeitado: "Rejeitado",
    released: "Liberado",
    returned: "Devolvido",
    returned_for_correction: "Devolvido para Correção",
    sample_received: "Amostra Recebida",
    sample_requested: "Amostra Solicitada",
    sample_sent: "Amostra Enviada",
    standardized: "Padronizado",
    suspended: "Suspenso",
    terminated: "Encerrado",
    total_received: "Recebido Total",
    trialperiod: "Período de Teste",
    under_bidding: "Em Disputa",
    under_evaluation: "Em Avaliação",
    under_qualification: "Em Habilitação",
    under_quotation: "Em Cotação",
    em_cotacao: "Em Cotação",
    under_review: "Em Revisão",
    underreview: "Em Revisão",
    delayed: "Atrasado",
    late: "Atrasado",
    overdue: "Atrasado",
    atrasado: "Atrasado",
    lost: "Extraviado",
    extraviado: "Extraviado"
};

export const STATUS_COLOR_MAP = {
    Ativo: "#0f4f4c",
    Alterado: "#12635e",
    Aprovado: "#177972",
    Arquivado: "#8fa9a5",
    Disponível: "#1b8f86",
    "Aguardando Aprovação": "#22a69b",
    "Aguardando Julgamento": "#40b8ad",
    "Aguardando Resposta de Envio Parcial": "#40b8ad",
    "Aguardando Qualificação": "#12635e",
    "Aguardando Envio": "#63c9c0",
    "Aguardando Complemento": "#22a69b",
    "Em Recebimento": "#1b8f86",
    Bloqueado: "#0e4946",
    Ocupado: "#40b8ad",
    Cancelado: "#0e4946",
    Cash: "#1b8f86",
    Fechado: "#93a9a6",
    Concluido: "#177972",
    Concluído: "#177972",
    Entregue: "#177972",
    Desclassificado: "#93a9a6",
    Rascunho: "#b4c6c3",
    Habilitado: "#177972",
    Expirado: "#93a9a6",
    Falhou: "#0e4946",
    "Totalmente Enviado": "#177972",
    "Totalmente Utilizado": "#177972",
    "Em Progresso": "#1b8f86",
    "In-store": "#2F80ED",
    "Em Revisão": "#22a69b",
    "Em Distribuição": "#1b8f86",
    "Em Treinamento": "#63c9c0",
    "Em Trânsito": "#40b8ad",
    Inativo: "#93a9a6",
    Inabilitado: "#0e4946",
    Integrado: "#0f4f4c",
    Convidado: "#1b8f86",
    Faturado: "#177972",
    "Item Implantado": "#177972",
    "Em Julgamento": "#40b8ad",
    "Em Manutenção": "#22a69b",
    "Em Revisão Mundimed": "#22a69b",
    "Sem Propostas": "#93a9a6",
    "Não Aprovado": "#0e4946",
    Offline: "#93a9a6",
    Online: "#27AE60",
    "Walk-in": "#4f86c6",
    "Em Pausa": "#22a69b",
    Afastado: "#93a9a6",
    Aberto: "#1b8f86",
    Outlet: "#F2994A",
    "Recebido Parcial": "#1b8f86",
    "Envio Parcial Aprovado": "#177972",
    "Envio Parcial Rejeitado": "#0e4946",
    "Parcialmente Entregue": "#1b8f86",
    "Parcialmente Vigente": "#1b8f86",
    "Parcialmente Faturado": "#1b8f86",
    "Parcialmente Devolvido": "#40b8ad",
    "Parcialmente Enviado": "#1b8f86",
    "Parcialmente Utilizado": "#1b8f86",
    "Senha Expirada": "#0e4946",
    Pendente: "#22a69b",
    "Aguardando Ativação": "#22a69b",
    "Aguardando Exclusão": "#0e4946",
    "Separação em Andamento": "#1b8f86",
    Qualificado: "#177972",
    "Aguardando Empenho": "#22a69b",
    "Ordem de Compra Gerada": "#177972",
    Cotado: "#1b8f86",
    Rejeitado: "#0e4946",
    Liberado: "#177972",
    Devolvido: "#40b8ad",
    "Devolvido para Correção": "#40b8ad",
    "Amostra Recebida": "#177972",
    "Amostra Solicitada": "#22a69b",
    "Amostra Enviada": "#1b8f86",
    Padronizado: "#177972",
    Suspenso: "#0e4946",
    Encerrado: "#93a9a6",
    "Recebido Total": "#177972",
    "Período de Teste": "#1b8f86",
    "Em Disputa": "#1b8f86",
    "Em Avaliação": "#22a69b",
    "Em Habilitação": "#1b8f86",
    "Em Cotação": "#1b8f86",
    Atrasado: "#12635e",
    Extraviado: "#8b1e3f",
    "Sem status": "#7b8e8c",
    Desconhecido: "#5f7572"
};

const STATUS_SLUG_ALIASES = {
    finalizado: "finalized",
    expedicao_envio: "invoiced",
    expedicao: "invoiced",
    envio: "invoiced",
    em_cotacao: "under_quotation",
    rejeitado: "rejected",
    entregue: "delivered",
    concluido: "completed",
    atrasado: "pending",
    cancelado: "cancelled",
    em_transporte: "in_transit"
};

export const getNormalizedStatusToken = (value) => normalizeStatusToken(value);

export const normalizeStatusLabel = (value, options = {}) => {
    const { fallback = "Desconhecido" } = options;
    const token = normalizeStatusToken(value);

    if (!token) return fallback;

    return STATUS_LABELS[token] || fallback;
};

export const slugifyStatus = (value) => {
    const token = normalizeStatusToken(value);

    if (!token) return "";

    return STATUS_SLUG_ALIASES[token] || token;
};
